### ISSUE TITLE
No sound under Linux

### ISSUE THREAD

**Issue by chris-y** [calmopyrin/tedplay#3]
I've built this for Linux using the Makefile in #2 (with -fpermissive added).  It builds fine, but playing any .prg file from the HVTC collection gives the same output and no audio.  I've built it on a Raspberry Pi, and on an Intel laptop and both have exactly the same result.

````
SDL_OpenAudio success!
Using audio driver : pulseaudio
Type:         Other
Chip:         Unknown
Module:       HVTC/musicians/southern_shaun/tutti_frutti.prg
Author:       Unknown
Released:     Unknown
Total tunes:  1
Default tune: 1
Init        : $0000
Play address: $FE00
````

At this point the only available action is to press Ctrl-C to get back to the command line.

**Comment by calmopyrin** [comment]
You must load the PRG files in the 'player' directory, so something like:
/player/musicians/southern_shaun/tutti_frutti.prg
